routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\{LoginController, LogoutController, RegisterController} ;
use App\Http\Controllers\{DashboardController, HomeController, PostController, PostLikeController, QuoteController, 
    UserController, UserPostController};

// Redirect
Route::get('/', [HomeController::class, 'redirect']);

// Home
Route::get('/home', [HomeController::class,'indexHome'])->name('home');

// Register
Route::group([
    'prefix'        => '/register',
    'as'            => ''
], function () {
    Route::get('/', [RegisterController::class, 'index'])->name('register');
    Route::post('/', [RegisterController::class, 'store']);
});

// Login
Route::group([
    'prefix'        => '/login',
    'as'            => ''
], function () {
    Route::get('/', [LoginController::class, 'index'])->name('login');
    Route::post('/', [LoginController::class, 'store']);
});

// Logout
Route::post('/logout', [LogoutController::class, 'store'])->name('logout');

// Quotes 
Route::group([
    'middleware'    => 'auth',
    'prefix'        => '/quotes',
    'as'            => ''
], function () {
    Route::get('/', [QuoteController::class, 'index'])->name('quotes');
    Route::post('/', [QuoteController::class, 'store']);
});


// Post
Route::group([
    'prefix'        => '/posts',
    'as'            => ''
], function () {
    Route::get('/', [PostController::class, 'index'])->name('posts')->middleware('auth');
    Route::post('/', [PostController::class, 'store'])->name('posts');
    Route::get('search', [PostController::class, 'search'])->name('search');
    Route::delete('{post}/delete', [PostController::class, 'destroy'])->name('posts.destroy');
    Route::get('{slug}', [PostController::class, 'show'])->name('posts.show');
    Route::get('{slug}/edit', [PostController::class, 'edit'])->name('posts.edit');
    Route::put('{id}/update', [PostController::class, 'update'])->name('posts.update');
    Route::post('{post}/likes', [PostLikeController::class, 'store'])->name('posts.likes');
    Route::delete('{post}/dislikes', [PostLikeController::class, 'destroy'])->name('posts.dislikes');
});


Route::get('/users/{user:username}/posts', [UserPostController::class, 'index'])->name('users.posts');

Route::get('/search', [PostController::class, 'search'])->name('search');

Route::controller(UserController::class)->group(function() {
// User profile
Route::get('/user/{user:username}/profile', [UserController::class, 'show'])->name('users.profile');
// Users edit
Route::put('/user/{id}/update', [UserController::class, 'update'])->name('users.update');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $path = '/storage/profile_images/';

    public function getPictureAttribute($picture) {

        return $this->path . $picture;

    }

    protected $path2 = "/img/";

    public function getRandomAttribute($picture) {
        return $this->path2 . $picture;

    }

    protected $guarded = [];

    public function posts() {
        return $this->hasMany(Post::class);
    }

    public function likes() {
        return $this->hasMany(Like::class);
    }

    public function receivedLikes() {
        return $this->hasManyThrough(Like::class, Post::class);
    }

    public function quotes() {
        return $this->hasMany(Quote::class);
    }
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    // protected $fillable = [
    //     'name',
    //     'email',
    //     'password',
    //     'username',
    // 
    // ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/dashboard.blade.php
@extends('layouts.app')

<title>Dashboard</title>

@section('content')

<div id="loader"></div>

<div style="display:none;" id="myDiv">

<div class="flex justify-center">
<div class="w-8/12 bg-white p-6 rounded-sm">
Dashboard
</div>

</div>
    
@endsection

resources/views/home.blade.php
@extends('layouts.app')

<title>Home</title>

@section('content')

<div id="loader"></div>

<div style="display:none;" id="myDiv">

<div class="flex justify-center">
<div class="w-8/12 bg-white p-6 rounded-sm">

@if (session()->has('logged-in'))
<div class="bg-green-500 p-1 rounded-sm mb-6 text-white text-center">
    {{session('logged-in')}}
</div>
@endif

@if (session()->has('registered'))
<div class="bg-green-500 p-1 rounded-sm mb-6 text-white text-center">
    {{session('registered')}}
</div>
@endif

<h1 class="font-bold">Welcome back<span class="text-blue-700">{{Auth::check() ? ' ' . Auth::user()->name : ' there!'}}</span></h1>
<p class="mt-2">How are you today..? I have an quote for you, hope you will like it &#128512;</p>
<p class="mt-2 mb-2 text-rose-500">Quote:</p>

@if ($quote)

<p>"{{$quote->body}}" - <span style="font-style: italic">{{$quote->author}}</span></p>

@else

<p>There are no quotes at the moment..</p>

@endif

</div>

</div>

<div class="flex justify-center mt-5">

<div class="container">

  @foreach ($posts as $post)
  <div class="card">
    <div class="card__header">
      <img src="{{$post->picture == 'no-picture' ? $post->placeholder : '/storage/images/posts/' . $post->picture}}" alt="Post Image" class="card__image" width="600">
    </div>
    <div class="card__body" style="text-align: justify">
      <h4><a href="{{route('posts.show', $post->slug)}}">{{$post->title}}</a></h4>
      @if (strlen($post->body) >= '200') 
        <p style="text-align: justify">{!! substr($post->body,0,200) !!} ...</p>
      @else 
        <p style="text-align: justify">{!! $post->body !!} </p>
      @endif
      <a href="{{route('posts.show', $post->slug)}}"> <button class="text-white bg-green-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Read full article</button> </a>
    </div>
    <div class="card__footer">
      <div class="user">
      <img style="height: 40px" 
      src="{{$post->user->picture == "/storage/profile_images/no-picture" ? $post->user->random : $post->user->picture}}"
      alt="User Image" class="user__image">
        <div class="user__info">
          <h5>{{$post->user->name}}</h5>
          <small>{{$post->created_at->diffForHumans()}}</small>
        </div>
      </div>
    </div>
  </div>
  @endforeach
</div>

</div>

</div>








@endsection

resources/views/search.blade.php
@extends('layouts.app')

<title>Search posts..</title>

@section('content')

<div class="flex justify-center">
<div class="w-8/12 bg-white p-6 rounded-sm">


    <form class="flex items-center" action="{{route('search')}}" method="GET">   

        <div class="relative w-full">
            <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
            </div>
            <input type="text" id="query" name="query" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-white dark:border-gray-600 dark:placeholder-gray-400 dark:text-black dark:focus:ring-blue-500 dark:focus:border-blue-500" 
            placeholder="Search results for {{$searched}}">
        </div>
        <button type="submit" class="p-2.5 ml-2 text-sm font-medium text-white bg-blue-700 rounded-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg></button>
    </form>



@if ($posts->count())

@foreach ($posts as $post)

<x-post :post="$post"></x-post>
    
@endforeach



@else

<p>
    There are no posts with that search right now at the moment.. 
    <br> 
    Try again..
</p>

<img 
class="h-52 mt-2"
src="img/error.gif" 
alt="Error"
title="Error">
    
@endif

</div>
</div>
    
@endsection